### ISSUE TITLE
Types with [JsonIgnore] (or similar) are not ignored

### ISSUE THREAD

**Issue by xwipeoutx** [gkinsman/Typescriptr#20]
If I have a class
```cs
public class Foo {
  public int Present { get; set; }
  [JsonIgnore] public string Absent { get; set; }
}
```
I should be able to configure it to ignore the `Absent` property.

(PR coming soon)

**Comment by gkinsman** [comment]
Thanks Steve, have merged this in and should be available on the nugets as [`1.5.0`](https://www.nuget.org/packages/Typescriptr/1.5.0) as soon as it passes validation.
