### ISSUE TITLE
Confusing docs

### ISSUE THREAD

**Issue by xwipeoutx** [gkinsman/Typescriptr#22]
Regarding these docs:
https://github.com/gkinsman/Typescriptr#notes-2

I don't understand what it means at all - this is under the member filtering section (thanks for adding docs btw :+1:).  Is it meant to be for `IEnumerable`? 

> **Notes**
> As with IDictionary types, it is recommended to not have API types inherit directly from the interface, but to have properties of the type, else the expected output doesn't make much sense.

**Comment by gkinsman** [comment]
Ah thanks! That's what I get for trying to update the docs on my phone 😄. Have swapped them around, and adjusted the IEnumerable notes for clarity.
